- .idea/.name
- .idea/compiler.xml
- .idea/encodings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- pom.xml
- src/main/java/ch/heigvd/res/chill/Chill.java
- src/test/java/ch/heigvd/res/chill/ChillTest.java
- test-cycle.iml
> Publish skeleton

- chill.iml
- src/main/java/ch/heigvd/res/chill/Bartender.java
- src/test/java/ch/heigvd/res/chill/BartenderTest.java
I have implemented a crude version of Bartender. I don't use messages and only strings, but it does the job for now.
> First version of bartender greetings

- src/main/java/ch/heigvd/res/chill/domain/wasadigi/Duvel.java
- src/test/java/ch/heigvd/res/chill/domain/wasadigi/DuvelTest.java
> Add Duvel with tests

- src/main/java/ch/heigvd/res/chill/domain/wasadigi/Boxer.java
- src/test/java/ch/heigvd/res/chill/domain/wasadigi/BoxerTest.java
Please have a look at my proposal. It should close #13 .
> Add Boxer to the menu, with tests

- .idea/misc.xml
- src/main/java/ch/heigvd/res/chill/domain/pete842/Torpille.java
- src/test/java/ch/heigvd/res/chill/domain/pete842/TorpilleTest.java
Add "Torpille" beer (BFM) with its JUnit test.
> Add Torpille with JUnit test

- .idea/misc.xml
- src/main/java/ch/heigvd/res/chill/domain/pete842/Quollfrisch.java
- src/test/java/ch/heigvd/res/chill/domain/pete842/QuollfrischTest.java
Add "Quollfrish" beer with its JUnit test.
> Add Quollfrisch with JUnit test

- src/main/java/ch/heigvd/res/chill/domain/Ezehkiel/Hoegaarden.java
- src/test/java/ch/heigvd/res/chill/domain/Ezehkiel/HoegaardenTest.java
> Added Hoegaarden

- src/main/java/ch/heigvd/res/chill/domain/waltharnack/Kwak.java
- src/test/java/ch/heigvd/res/chill/domain/waltharnack/KwakTest.java
> add Kwak and its tests

- src/main/java/ch/heigvd/res/chill/domain/jackeri/GoldenSirup.java
- src/test/java/ch/heigvd/res/chill/domain/jackeri/GoldenSirupTest.java
Golden sirup added. References  #27
> Golden sirup code & test

- src/main/java/ch/heigvd/res/chill/domain/waltharnack/Kriek.java
- src/test/java/ch/heigvd/res/chill/domain/waltharnack/KriekTest.java
Kriek implemented, tests passed
> add Kriek and its tests

- .idea/misc.xml
- src/main/java/ch/heigvd/res/chill/domain/jzaehrin/TacticalNuclearPenguin.java
- src/test/java/ch/heigvd/res/chill/domain/jzaehrin/TacticalNuclearPenguinTest.java
> Add Tactical Nuclear Penguin Beer and test

- .idea/misc.xml
- src/main/java/ch/heigvd/res/chill/domain/jzaehrin/Leevike.java
- src/test/java/ch/heigvd/res/chill/domain/jzaehrin/LeevikeTest.java
> Add Leevike beer and test

- .idea/misc.xml
- src/main/java/ch/heigvd/res/chill/domain/jzaehrin/Sajand.java
- src/test/java/ch/heigvd/res/chill/domain/jzaehrin/SajandTest.java
> Add Sajand beer and test

- .idea/misc.xml
- src/main/java/ch/heigvd/res/chill/domain/jzaehrin/SinkTheBismarck.java
- src/test/java/ch/heigvd/res/chill/domain/jzaehrin/SinkTheBismarckTest.java
> Add Sink the Bismarck beer and test

- src/main/java/ch/heigvd/res/chill/domain/XBrast/AlexLeRouge.java
- src/test/java/ch/heigvd/res/chill/domain/XBrast/AlexLeRougeTest.java
> add Alex Le Rouge

- src/main/java/ch/heigvd/res/chill/domain/mercierjo/Adelscott.java
- src/test/java/ch/heigvd/res/chill/domain/mercierjo/AdelscottTest.java
> Add Adelscott with tests

- src/main/java/ch/heigvd/res/chill/domain/andresMoreno96/Heineken.java
- src/test/java/ch/heigvd/res/chill/domain/andresMoreno96/HeinekenTest.java
> Add Heineken with tests

- src/main/java/ch/heigvd/res/chill/domain/andresMoreno96/Quilmes.java
- src/test/java/ch/heigvd/res/chill/domain/andresMoreno96/QuilmesTest.java
> Add Quilmes with tests

- src/main/java/ch/heigvd/res/chill/domain/Jostoph/Leffe.java
- src/test/java/ch/heigvd/res/chill/domain/Jostoph/LeffeTest.java
I have added the Leffe to the beer choice.
> Add Leffe beer with test

- chill.iml
- src/main/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/Brakina.java
- src/test/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/BrakinaTest.java
Please take a look at my proposal. I'm not sure why the chill.iml. This should close #61
> Add Brakina with tests

- src/main/java/ch/heigvd/res/chill/domain/lionelburgbach/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/lionelburgbach/GuinnessTest.java
- src/test/java/ch/heigvd/res/chill/domain/wasadigi/PunkIPATest.java
> Add Guinness with tests

- src/main/java/ch/heigvd/res/chill/domain/andresMoreno96/DragonBeer.java
- src/test/java/ch/heigvd/res/chill/domain/andresMoreno96/DragonBeerTest.java
> Add DragonBeer with tests

- src/main/java/ch/heigvd/res/chill/domain/lionelburgbach/Barbar.java
- src/test/java/ch/heigvd/res/chill/domain/lionelburgbach/BarbarTest.java
It should be good. Take a look! #78
> Add Barbar with tests

- src/main/java/ch/heigvd/res/chill/domain/ercclpn/Tiger.java
- src/test/java/ch/heigvd/res/chill/domain/ercclpn/TigerTest.java
Please have a look at my code.
> Add Tiger beer and unit tests

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/Kadji.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/KadjiTest.java
> Add Kadji with tests

- src/main/java/ch/heigvd/res/chill/domain/lionelburgbach/Eve.java
- src/test/java/ch/heigvd/res/chill/domain/lionelburgbach/EveTest.java
It should be ok, I will by one! You can close #97
> Add Eve with tests

- src/main/java/ch/heigvd/res/chill/domain/playjul306/SuperBock.java
- src/test/java/ch/heigvd/res/chill/domain/playjul306/SuperBockTest.java
I created a Super Bock. Closes #99
> Add Super Bock with tests

- src/main/java/ch/heigvd/res/chill/domain/volkan05/Boxer2.java
- src/test/java/ch/heigvd/res/chill/domain/volkan05/Boxer2Test.java
Boxer2 was created. Closes #102
> Add a new Boxer

- src/main/java/ch/heigvd/res/chill/domain/nyg/Mythos.java
- src/test/java/ch/heigvd/res/chill/domain/nyg/MythosTest.java
The Mythos beer has been added, this should close #108.
> Added the Greek Mythos beer with tests.

- src/main/java/ch/heigvd/res/chill/domain/edinem/SarajevskoPivo.java
- src/test/java/ch/heigvd/res/chill/domain/edinem/SarajevkoPivoTest.java
> Add sarajevsko pivo

- src/main/java/ch/heigvd/res/chill/domain/mbonjour/EndOfTheWorld.java
- src/test/java/ch/heigvd/res/chill/domain/mbonjour/EndOfTheWorldTest.java
I wanted the End Of The World beer to this project so here it goes !
This closes #114
> Adding the End Of The World Beer to the project

- src/main/java/ch/heigvd/res/chill/domain/edinem/NiksickoPivo.java
- src/test/java/ch/heigvd/res/chill/domain/edinem/NiksickoPivoTest.java
niksicko pivo added. Closes #117
> Add niksicko pivo

- src/main/java/ch/heigvd/res/chill/domain/nyg/Schlenkerla.java
- src/test/java/ch/heigvd/res/chill/domain/nyg/SchlenkerlaTest.java
> Added the Schlenkerla smoked beer.

- src/main/java/ch/heigvd/res/chill/domain/edinem/Jelen.java
- src/test/java/ch/heigvd/res/chill/domain/edinem/JelenTest.java
> added jelen beer

- src/main/java/ch/heigvd/res/chill/domain/mbonjour/CuveeDesTrolls.java
- src/test/java/ch/heigvd/res/chill/domain/mbonjour/CuveeDesTrollsTest.java
I've added "La Cuvée des Trolls" to this project which is a great beer.
This closes #129
> Adding La Cuvée des Trolls Beer to the project

- src/main/java/ch/heigvd/res/chill/domain/nyg/Fix.java
- src/test/java/ch/heigvd/res/chill/domain/nyg/FixTest.java
This is a fix for the Fix beer. Closes #135.
> Fix for the Fix beer.

- src/main/java/ch/heigvd/res/chill/domain/nathan/seville/Brooklyn.java
- src/test/java/ch/heigvd/res/chill/domain/nathan/seville/BrooklynTest.java
I have implemented the Brooklyn beer. Add it for good afterwork. Closes #118
> Best beer in town

- src/main/java/ch/heigvd/res/chill/domain/Obyka/Pirate.java
- src/test/java/ch/heigvd/res/chill/domain/Obyka/PirateTest.java
I'm happy now. Should close #143
> Add pirate beer with tests.

- src/main/java/ch/heigvd/res/chill/domain/lapinousexy/Beer1664.java
- src/test/java/ch/heigvd/res/chill/domain/lapinousexy/Beer1664Test.java
> Added beer 1664 with tests

- src/main/java/ch/heigvd/res/chill/domain/briskocube/Busch.java
- src/test/java/ch/heigvd/res/chill/domain/briskocube/BuschTest.java
> Added the awful beer Busch with tests

- src/main/java/ch/heigvd/res/chill/domain/lougranou/Rochefort.java
- src/test/java/ch/heigvd/res/chill/domain/lougranou/RochefortTest.java
please take a look at my proposal, I've completed one trappist beer #148
> Add Trappiste Rochefort beer

- src/main/java/ch/heigvd/res/chill/domain/briskocube/Kwak.java
- src/test/java/ch/heigvd/res/chill/domain/briskocube/KwakTest.java
> kwak added with tests

- src/main/java/ch/heigvd/res/chill/domain/nathan/seville/Delirium.java
- src/test/java/ch/heigvd/res/chill/domain/nathan/seville/DeliriumTest.java
I've implemented the Delirium. Quite a good Belgian beer as many others. Closes #144
> Belgian beers are really good

- chill.iml
- src/main/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/Adler.java
- src/test/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/AdlerTest.java
Please take a look at my proposal. This should close #122
> Add adler with tests

- src/main/java/ch/heigvd/res/chill/domain/isaiaSpinelli/Gerardi.java
- src/test/java/ch/heigvd/res/chill/domain/isaiaSpinelli/GerardiTest.java
Implémentation de la bière Gerardi
> Implement Gerardi with test

- src/main/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/Singha.java
- src/test/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/SinghaTest.java
Please take a look at my proposal. This should close #161
> Add Singha with tests

- src/main/java/ch/heigvd/res/chill/domain/NatMiz/Asahi.java
- src/test/java/ch/heigvd/res/chill/domain/NatMiz/AsahiTest.java
> Asahi with tests

- src/main/java/ch/heigvd/res/chill/domain/lapinousexy/Leffe.java
- src/test/java/ch/heigvd/res/chill/domain/lapinousexy/LeffeTest.java
Added Leffe with tests. Closes #171
> Added Leffe with tests

- src/main/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/Seybrew.java
- src/test/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/SeybrewTest.java
Please take a look at my proposal. This should close #178
> Add Seybrew with test

- src/main/java/ch/heigvd/res/chill/domain/volkan05/Beer1664.java
- src/test/java/ch/heigvd/res/chill/domain/volkan05/Beer1664Test.java
> Adding new 1664

- src/main/java/ch/heigvd/res/chill/domain/gaeba95/FantaRose.java
- src/test/java/ch/heigvd/res/chill/domain/gaeba95/FantaRoseTest.java
> Adding Fanta Rose

- src/main/java/ch/heigvd/res/chill/domain/gaeba95/FantaViolet.java
- src/test/java/ch/heigvd/res/chill/domain/gaeba95/FantaVioletTest.java
> Adding fanta violet

- src/main/java/ch/heigvd/res/chill/domain/lougranou/GuldenDraak.java
- src/test/java/ch/heigvd/res/chill/domain/lougranou/GuldenDraakTest.java
Please have a look on my second beer #148
> Add Gulden Draak beer with tests

- src/main/java/ch/heigvd/res/chill/domain/lougranou/Kwak.java
- src/test/java/ch/heigvd/res/chill/domain/lougranou/KwakTest.java
Add my third beer, it should close #148
> add Kwak with test

- src/main/java/ch/heigvd/res/chill/domain/lionelburgbach/Mecklenburgische.java
- src/test/java/ch/heigvd/res/chill/domain/lionelburgbach/MecklenburgischeTest.java
It was really hard, but it's done! hope you like it.
> Add Mecklenburgische with tests

- src/main/java/ch/heigvd/res/chill/domain/Laykel/AppleJuice.java
- src/test/java/ch/heigvd/res/chill/domain/Laykel/AppleJuiceTest.java
Closes #212 (for real this time... hopefully)
> Added apple juice, for soft pleasures

- src/main/java/ch/heigvd/res/chill/domain/jackeri/Arequipena.java
- src/test/java/ch/heigvd/res/chill/domain/jackeri/ArequipenaTest.java
> Create Arequipeña beer + tests

- src/main/java/ch/heigvd/res/chill/domain/lionelburgbach/Liechtensteiner.java
- src/test/java/ch/heigvd/res/chill/domain/lionelburgbach/LiechtensteinerTest.java
Done with pleasure. Take a look! #226
> Add Liechtensteiner with tests

- src/main/java/ch/heigvd/res/chill/domain/Laykel/Water.java
- src/test/java/ch/heigvd/res/chill/domain/Laykel/WaterTest.java
> Added water, it's tasteless but nice

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/Harp.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/HarpTest.java
> Add Harp with tests

- src/main/java/ch/heigvd/res/chill/domain/Tsimwi/VaultSweetPotatoAle.java
- src/test/java/ch/heigvd/res/chill/domain/Tsimwi/VaultSweetPotatoAleTest.java
> Add Sweet Potato Ale with tests

- src/main/java/ch/heigvd/res/chill/domain/Tsimwi/MilwaukeeBrewingSasquash.java
- src/test/java/ch/heigvd/res/chill/domain/Tsimwi/MilwaukeeBrewingSasquashTest.java
> Add Milwaukee Brewing Sasquash beer with tests

- src/main/java/ch/heigvd/res/chill/domain/edinem/Grimbergen.java
- src/test/java/ch/heigvd/res/chill/domain/edinem/GrimbergenTest.java
> Grimbergen added. Tests ok

- src/main/java/ch/heigvd/res/chill/domain/mbonjour/TheBeer.java
- src/test/java/ch/heigvd/res/chill/domain/mbonjour/TheBeerTest.java
This PR add TheBeer to the project and closes #252
> adding TheBeer to this project

- src/main/java/ch/heigvd/res/chill/domain/wasadigi/Artisanale.java
- src/test/java/ch/heigvd/res/chill/domain/wasadigi/ArtisanaleTest.java
I have implemented a crude version of Artisanale.
> First version of Artisanal beer

- src/main/java/ch/heigvd/res/chill/domain/playjul306/SmartBeer.java
- src/test/java/ch/heigvd/res/chill/domain/playjul306/SmartBeerTest.java
I created a SmartBeer. Closes #270
> Add SmartBeer with tests

- src/main/java/ch/heigvd/res/chill/domain/Ezehkiel/KlinskoyeSvetloe.java
- src/test/java/ch/heigvd/res/chill/domain/Ezehkiel/KlinskoyeSvetloeTest.java
> Added KlinskoyeSvetloe with test

- src/Test/java/ch/heigvd/res/chill/domain/Tsimwi/SmokedPumpkinCaperTest.java
- src/main/java/ch/heigvd/res/chill/domain/Tsimwi/SmokedPumpkinCaper.java
> Added Smoked Pumpkin Caper beer with tests

- src/main/java/ch/heigvd/res/chill/domain/isaiaSpinelli/Galouchette.java
- src/test/java/ch/heigvd/res/chill/domain/isaiaSpinelli/GalouchetteTest.java
> Add Galouchette with test

- src/main/java/ch/heigvd/res/chill/domain/Crulllo/Pinchaut.java
- src/test/java/ch/heigvd/res/chill/domain/Crulllo/PinchautTest.java
> Added a new beer called Pinchaut

- src/main/java/ch/heigvd/res/chill/domain/BasileBotebol/Westvleteren.java
- src/test/java/ch/heigvd/res/chill/domain/BasileBotebol/WestvleterenTest.java
> Add Westvleteren with tests

- src/Test/java/ch/heigvd/res/chill/domain/Cell00phane/DuffTest.java
- src/main/java/ch/heigvd/res/chill/domain/Cell00phane/Duff.java
> Add Duff with tests

- src/main/java/ch/heigvd/res/chill/domain/Ichimizu/Pipolimbo.java
- src/test/java/ch/heigvd/res/chill/domain/Ichimizu/PipolimboTest.java
> Add Pipolimbo with tests

- src/main/java/ch/heigvd/res/chill/domain/Jostoph/Boucanier.java
- src/test/java/ch/heigvd/res/chill/domain/Jostoph/BoucanierTest.java
> Add Boucanier beer with basic tests

- src/Test/java/ch/heigvd/res/chill/domain/Tsimwi/RobohopTest.java
- src/main/java/ch/heigvd/res/chill/domain/Tsimwi/Robohop.java
> Robohop beer added with tests

- src/main/java/ch/heigvd/res/chill/domain/mercierjo/Adelscott.java
- src/main/java/ch/heigvd/res/chill/domain/mercierjo/Somersby.java
- src/test/java/ch/heigvd/res/chill/domain/mercierjo/AdelscottTest.java
- src/test/java/ch/heigvd/res/chill/domain/mercierjo/SomersbyTest.java
> Add Somersby with its tests

- src/Test/java/ch/heigvd/res/chill/domain/MichaelDaSilva/CoralLagerTest.java
- src/main/java/ch/heigvd/res/chill/domain/MichaelDaSilva/CoralLager.java
I have added the Coral Branca Lager beer in the selection of beers.
> Add Coral Branca Lager for Chill Protocol

- src/main/java/ch/heigvd/res/chill/domain/IxSysTech/Jelen.java
- src/test/java/ch/heigvd/res/chill/domain/IxSysTech/JelenTest.java
I have implemented the new beer Jelen.
> Add beer Jelen

- src/main/java/ch/heigvd/res/chill/domain/tatallias/FinDuMonde.java
- src/test/java/ch/heigvd/res/chill/domain/tatallias/FinDuMondeTest.java
> Add Fin du Monde with tests

- src/main/java/ch/heigvd/res/chill/domain/XBrast/Sagres.java
- src/test/java/ch/heigvd/res/chill/domain/XBrast/SagresTest.java
i have implemented a beer Sagres
> first version of beer of Sagres

- src/test/java/ch/heigvd/res/chill/domain/CosmicElodie/LagerTest.java
> Add Lager with correct path test

- src/main/java/ch/heigvd/res/chill/domain/isaiaSpinelli/Miguel.java
- src/test/java/ch/heigvd/res/chill/domain/isaiaSpinelli/MiguelTest.java
> Add Miguel

- src/main/java/ch/heigvd/res/chill/domain/Rafiibro/Rafii.java
- src/test/java/ch/heigvd/res/chill/domain/Rafiibro/RafiiTest.java
Added my own beer, i'm so happy !
> Adding Rafii Beer

- src/main/java/ch/heigvd/res/chill/domain/Crulllo/Chabrulay.java
- src/test/java/ch/heigvd/res/chill/domain/Crulllo/ChabrulayTest.java
> Add Chabrulay

- src/Test/java/ch/heigvd/res/chill/domain/yoannsim/DocteurGabsTest.java
- src/main/java/ch/heigvd/res/chill/domain/yoannsim/DocteurGabs.java
> add docteur gab's

- src/main/java/ch/heigvd/res/chill/domain/oTwoWin/Grolsch.java
- src/test/java/ch/heigvd/res/chill/domain/oTwoWin/GrolschTest.java
> Added the beer Grolsch 

- src/main/java/ch/heigvd/res/chill/domain/SamuelMettler/HopHouseLager.java
- src/test/java/ch/heigvd/res/chill/domain/SamuelMettler/HopHouseLagerTest.java
> Add Hop House Lager with tests

- src/main/java/ch/heigvd/res/chill/domain/CosmicElodie/BlueMoon.java
- src/test/java/ch/heigvd/res/chill/domain/CosmicElodie/BlueMoonTest.java
> Add Blue Moon with tests

- src/Test/java/ch/heigvd/res/chill/domain/pagedidier/GuinnessTest.java
- src/main/java/ch/heigvd/res/chill/domain/oTwoWin/Magnes.java
- src/test/java/ch/heigvd/res/chill/domain/oTwoWin/MagnesTest.java
I added the beer Magnes to the project.
> Adding the beer Magnes

- src/main/java/ch/heigvd/res/chill/domain/CosmicElodie/DogFish.java
- src/test/java/ch/heigvd/res/chill/domain/CosmicElodie/DogFishTest.java
> Add DogFish with tests

- src/Test/java/ch/heigvd/res/chill/domain/Cell00phane/ApolloniaTest.java
- src/main/java/ch/heigvd/res/chill/domain/Cell00phane/Apollonia.java
> Fb beerfest

- src/main/java/ch/heigvd/res/chill/domain/CosmicElodie/Athena.java
- src/test/java/ch/heigvd/res/chill/domain/CosmicElodie/AthenaTest.java
> Add Athena with tests

- src/main/java/ch/heigvd/res/chill/domain/Laykel/Butterbeer.java
- src/test/java/ch/heigvd/res/chill/domain/Laykel/ButterbeerTest.java
> Added option for butterbeer, and its tests

- src/main/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/Cristal.java
- src/test/java/ch/heigvd/res/chill/domain/mullerPierrickHeig/CristalTest.java
Please take a look at my proposal. This should close #367
> Add Cristal with tests

- src/main/java/ch/heigvd/res/chill/domain/StefanDejanovicHeig/Jelen.java
- src/test/java/ch/heigvd/res/chill/domain/StefanDejanovicHeig/JelenTest.java
> Add Jelen beer

- src/main/java/ch/heigvd/res/chill/domain/Eric_Noel/Berliner_Pilsner.java
- src/test/java/ch/heigvd/res/chill/domain/Eric_Noel/Berliner_Pilsner_Test.java
added Berliner Pilsner
close #425
> fb-Berliner_Pilsner

- src/main/java/ch/heigvd/res/chill/domain/Ezehkiel/BlackTea.java
- src/test/java/ch/heigvd/res/chill/domain/Ezehkiel/BlackTeaTest.java
We now have black tea and this closes #172
> fb-blacktea

- src/main/java/ch/heigvd/res/chill/domain/MaximilianCVogel/SweetBabyJesus.java
- src/test/java/ch/heigvd/res/chill/domain/MaximilianCVogel/SweetBabyJesusTest.java
> added sweet baby jesus

- src/main/java/ch/heigvd/res/chill/domain/RobelT/ChickenBeer.java
- src/test/java/ch/heigvd/res/chill/domain/RobelT/ChickenBeerTest.java
> ChickenBeer

- src/main/java/ch/heigvd/res/chill/domain/tatallias/SnakeBite.java
- src/test/java/ch/heigvd/res/chill/domain/tatallias/SnakeBiteTest.java
> Adding SnakeBite with test

- src/main/java/ch/heigvd/res/chill/domain/boosterloop/PinkPony.java
- src/test/java/ch/heigvd/res/chill/domain/boosterloop/PinkPonyTest.java
> Added Pink Pony with tests

- src/main/java/ch/heigvd/res/chill/domain/texx94/Coopers.java
- src/test/java/ch/heigvd/res/chill/domain/texx94/CoopersTest.java
> Coopers disponible

- src/main/java/ch/heigvd/res/chill/domain/mtutic/Karlovacko.java
- src/test/java/ch/heigvd/res/chill/domain/mtutic/KarlovackoTest.java
> Add Karlovacko with tests

- src/main/java/ch/heigvd/res/chill/domain/naetheline/Casaniere.java
- src/test/java/ch/heigvd/res/chill/domain/naetheline/CasaniereTest.java
> Correct the name of the beer.

- src/main/java/ch/heigvd/res/chill/domain/ClaudeAlves/BierZwei.java
- src/test/java/ch/heigvd/res/chill/domain/ClaudeAlves/BierZweiTest.java
> Add BierZwei

- src/main/java/ch/heigvd/res/chill/domain/jackeri/Cusquena.java
- src/test/java/ch/heigvd/res/chill/domain/jackeri/CusquenaTest.java
> Create Cusqueña beer + tests

- src/main/java/ch/heigvd/res/chill/domain/Thorkal/Gapeno.java
- src/test/java/ch/heigvd/res/chill/domain/Thorkal/GapenoTest.java
Everything needed for Gapeno beer
> Gapeno beer

- src/main/java/ch/heigvd/res/chill/domain/naetheline/Paulaner.java
- src/test/java/ch/heigvd/res/chill/domain/naetheline/PaulanerTest.java
> Paulaner implemantation and tests

- src/main/java/ch/heigvd/res/chill/domain/waltharnack/BirraMoretti.java
- src/test/java/ch/heigvd/res/chill/domain/waltharnack/BirraMoretti.java
> add Birra Moretti and its tests

- src/main/java/ch/heigvd/res/chill/domain/CosmicElodie/IceTeaMigros.java
- src/test/java/ch/heigvd/res/chill/domain/CosmicElodie/IceTeaMigrosTest.java
> Add Ice Tea Migros with tests

- src/main/java/ch/heigvd/res/chill/domain/playjul306/Nebuleuse.java
- src/test/java/ch/heigvd/res/chill/domain/playjul306/NebuleuseTest.java
> add fixed to Nebuleuse

- src/main/java/ch/heigvd/res/chill/domain/XBrast/Sumol.java
- src/test/java/ch/heigvd/res/chill/domain/XBrast/SumolTest.java
Sumol has implemented close #413
> add Sumol with test

- src/main/java/ch/heigvd/res/chill/domain/zereddiamond/EchecAndMalt.java
- src/test/java/ch/heigvd/res/chill/domain/zereddiamond/DrGabsChameauTest.java
- src/test/java/ch/heigvd/res/chill/domain/zereddiamond/EchecAndMaltTest.java
I do not have ideas for another unit tests.
> Added Echec And Malt

- src/main/java/ch/heigvd/res/chill/domain/Koffi94/Chupacabra.java
- src/test/java/ch/heigvd/res/chill/domain/Koffi94/ChupacabraTest.java
> Third beer !

- src/main/java/ch/heigvd/res/chill/domain/wasadigi/LaFranche.java
- src/test/java/ch/heigvd/res/chill/domain/wasadigi/LaFrancheTest.java
Here is a feature for La Franche, to demonstrate how to fix feature branches NOT created from master.
> Fb lafranche

- src/main/java/ch/heigvd/res/chill/domain/wasadigi/LaCorne.java
- src/test/java/ch/heigvd/res/chill/domain/wasadigi/LaCorneTest.java
Please accept my feature (I am asking this without realizing that I created fb-lacorne when I was on fb-lafranche, and not on master... you will not be happy).
> Add La Corne, with tests

- src/main/java/ch/heigvd/res/chill/domain/zereddiamond/HoppyRoad.java
- src/test/java/ch/heigvd/res/chill/domain/zereddiamond/HoppyRoadTest.java
> Add new beer Hoppy Road

- src/main/java/ch/heigvd/res/chill/domain/Ichimizu/TheMuller.java
- src/test/java/ch/heigvd/res/chill/domain/Ichimizu/TheMullerTest.java
> add TheMuller with tests

- src/main/java/ch/heigvd/res/chill/domain/Ezehkiel/Nevskoe.java
- src/test/java/ch/heigvd/res/chill/domain/Ezehkiel/NevskoeTest.java
> Added Nevskoe beer with test

- src/main/java/ch/heigvd/res/chill/domain/Tsimwi/BaltikaDark.java
- src/test/java/ch/heigvd/res/chill/domain/Tsimwi/BaltikaDarkTest.java
> Add Baltika Dark with tests

- src/main/java/ch/heigvd/res/chill/domain/NatMiz/Suntory.java
- src/test/java/ch/heigvd/res/chill/domain/NatMiz/SuntoryTest.java
> Add Suntory with tests

- src/main/java/ch/heigvd/res/chill/domain/IxSysTech/Zajecarsko.java
- src/test/java/ch/heigvd/res/chill/domain/IxSysTech/ZajecarskoTest.java
I have implemented the beer Zajecarsko
> Implementation of the beer Zajecarsko

- src/main/java/ch/heigvd/res/chill/domain/SamuelMettler/Spatule.java
- src/test/java/ch/heigvd/res/chill/domain/SamuelMettler/SpatuleTest.java
> Added Spatule with tests

- src/main/java/ch/heigvd/res/chill/domain/IxSysTech/Lav.java
- src/test/java/ch/heigvd/res/chill/domain/IxSysTech/LavTest.java
I have implemented the beer Lav
> Add beer Lav

- src/main/java/ch/heigvd/res/chill/domain/SamuelMettler/Kilkenny.java
- src/test/java/ch/heigvd/res/chill/domain/SamuelMettler/KilkennyTest.java
> Added kilkenny with tests

- src/main/java/ch/heigvd/res/chill/domain/VictorTruan/Pilsen.java
- src/test/java/ch/heigvd/res/chill/domain/VictorTruan/PilsenTest.java
> Ajoute de la Pilsen

- src/main/java/ch/heigvd/res/chill/domain/MarionDL/Champagne.java
- src/test/java/ch/heigvd/res/chill/domain/MarionDL/ChampagneTest.java
> Added some champagne with class and test

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/Kir.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/KirTest.java
> Add kir with tests

- src/main/java/ch/heigvd/res/chill/domain/Ichimizu/Champomy.java
- src/test/java/ch/heigvd/res/chill/domain/Ichimizu/ChampomyTest.java
> adding Champomy

- src/main/java/ch/heigvd/res/chill/domain/lougranou/biereDuCanigou.java
- src/test/java/ch/heigvd/res/chill/domain/lougranou/biereDuCanigouTest.java
> Add Bière du Canigou and its tests

- src/main/java/ch/heigvd/res/chill/domain/zereddiamond/Calvinus.java
- src/test/java/ch/heigvd/res/chill/domain/zereddiamond/CalvinusTest.java
Sorry I made a mistake in the branch name. All tests passed.
> Add Calvinus

- src/main/java/ch/heigvd/res/chill/domain/Ichimizu/BotBeer.java
- src/test/java/ch/heigvd/res/chill/domain/Ichimizu/BotbeerTest.java
> Add fb-BotBeer

- src/main/java/ch/heigvd/res/chill/domain/lionelburgbach/Peroni.java
- src/test/java/ch/heigvd/res/chill/domain/lionelburgbach/PeroniTest.java
> Add peroni with tests

- src/main/java/ch/heigvd/res/chill/domain/lougranou/WestIndiesPorterGuinness.java
- src/test/java/ch/heigvd/res/chill/domain/lougranou/WestIndiesPorterGuinnessTest.java
> Add one exotic Guinness Export and its tests

- src/main/java/ch/heigvd/res/chill/domain/NatMiz/UrBock.java
- src/test/java/ch/heigvd/res/chill/domain/NatMiz/UrBockTest.java
> Add Ur-Bock with tests

- src/main/java/ch/heigvd/res/chill/domain/mercierjo/Kozel.java
- src/test/java/ch/heigvd/res/chill/domain/mercierjo/KozelTest.java
> Add kozel with tests

- src/main/java/ch/heigvd/res/chill/domain/mercierjo/Turborg.java
- src/test/java/ch/heigvd/res/chill/domain/mercierjo/TurborgTest.java
> Add Turborg with its tests

- src/main/java/ch/heigvd/res/chill/domain/MichaelDaSilva/Poncha.java
- src/test/java/ch/heigvd/res/chill/domain/MichaelDaSilva/PonchaTest.java
> Add Poncha

- src/main/java/ch/heigvd/res/chill/domain/Ichimizu/GiletJaune.java
- src/test/java/ch/heigvd/res/chill/domain/Ichimizu/GiletJauneTest.java
> GiletJaune with tests

- src/main/java/ch/heigvd/res/chill/domain/MarionDL/Prosecco.java
- src/test/java/ch/heigvd/res/chill/domain/MarionDL/ProseccoTest.java
> Adding Prosecco with tests

- src/main/java/ch/heigvd/res/chill/domain/Ichimizu/DragonBeer.java
- src/test/java/ch/heigvd/res/chill/domain/Ichimizu/DragonBeerTest.java
> Adding DragonBeer

- src/main/java/ch/heigvd/res/chill/domain/MichaelDaSilva/Narke.java
- src/test/java/ch/heigvd/res/chill/domain/MichaelDaSilva/NarkeTest.java
> Adding Närke Kaggen Stormaktsporter

- src/main/java/ch/heigvd/res/chill/domain/ecarpita93/Smirnoff.java
- src/test/java/ch/heigvd/res/chill/domain/ecarpita93/SmirnoffTest.java
Added Smirnoff beer with tests, this closes  #575
> Add Smirnoff with tests

- src/main/java/ch/heigvd/res/chill/domain/NatMiz/Fleurac.java
- src/test/java/ch/heigvd/res/chill/domain/NatMiz/FleuracTest.java
> Add Fleurac with tests

- src/main/java/ch/heigvd/res/chill/domain/isaiaSpinelli/Muse_beer.java
- src/test/java/ch/heigvd/res/chill/domain/isaiaSpinelli/Muse_beerTest.java
> Add Muse beer

- src/main/java/ch/heigvd/res/chill/domain/Tsimwi/CenovisBeer.java
- src/test/java/ch/heigvd/res/chill/domain/Tsimwi/CenovisBeerTest.java
> Add Cenovis Beer with tests

- src/main/java/ch/heigvd/res/chill/domain/BasileBotebol/Thirdbeer.java
- src/test/java/ch/heigvd/res/chill/domain/BasileBotebol/ThirdbeerTest.java
> Add Thirdbeer with test

- src/main/java/ch/heigvd/res/chill/domain/ecarpita93/Moretti.java
- src/test/java/ch/heigvd/res/chill/domain/ecarpita93/MorettiTest.java
Added Moretti beer with tests, this closes #602
> Add Moretti with tests

- src/main/java/ch/heigvd/res/chill/domain/ecarpita93/LaValona.java
- src/test/java/ch/heigvd/res/chill/domain/ecarpita93/LaValonaTest.java
Added La Valona beer, closes #596
> Add LaValona with tests

- src/main/java/ch/heigvd/res/chill/domain/panticne/Lav.java
- src/test/java/ch/heigvd/res/chill/domain/panticne/LavTest.java
> Add Lav with tests

- src/main/java/ch/heigvd/res/chill/domain/ercclpn/WinterBeer.java
- src/test/java/ch/heigvd/res/chill/domain/ercclpn/WinterBeerTest.java
Please have a look at my code.
> Add WinterBeer and all the tests

- src/main/java/ch/heigvd/res/chill/domain/zereddiamond/TroisDames.java
- src/test/java/ch/heigvd/res/chill/domain/zereddiamond/TroisDamesTest.java
More an another one and I will stop
> Added the beer Les Trois Dames

- src/main/java/ch/heigvd/res/chill/domain/Koffi94/Oppigards.java
- src/test/java/ch/heigvd/res/chill/domain/Koffi94/OppigardsTest.java
> Add forth beer -> Oppigards

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/Karlksrone.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/KarlksroneTest.java
> Add KarlKsrone with tests

- src/main/java/ch/heigvd/res/chill/domain/MichaelDaSilva/Pizza.java
- src/test/java/ch/heigvd/res/chill/domain/MichaelDaSilva/PizzaTest.java
Closes #628 - Adding food in the bar, some pizza
> Add pizza to the bar

- src/main/java/ch/heigvd/res/chill/domain/ercclpn/SpringBeer.java
- src/test/java/ch/heigvd/res/chill/domain/ercclpn/SpringBeerTest.java
Please look at my code, it should close #627
> Add Spring beer and tests

- src/main/java/ch/heigvd/res/chill/domain/Eric_Noel/Wubba_Lubba_Dub_Dub.java
- src/test/java/ch/heigvd/res/chill/domain/Eric_Noel/Wubba_Lubba_Dub_DubTest.java
Added Wubba Lubba Dub Dub
close #625
> Add Wubba Lubba Dub Dub

- src/main/java/ch/heigvd/res/chill/domain/volkan05/Cardinal.java
- src/test/java/ch/heigvd/res/chill/domain/volkan05/CardinalTest.java
Working on the problem with capital "T" in "Test" package.
> Volkan05 fb cardinal

- src/main/java/ch/heigvd/res/chill/domain/ga3tan/Heineken.java
- src/test/java/ch/heigvd/res/chill/domain/ga3tan/HeinekenTest.java
> added heineken with test

- src/main/java/ch/heigvd/res/chill/domain/BasileBotebol/Fourthbeer.java
- src/test/java/ch/heigvd/res/chill/domain/BasileBotebol/FourthbeerTest.java
> Add fourthbeer

- src/main/java/ch/heigvd/res/chill/domain/tatallias/LaMaudite.java
- src/test/java/ch/heigvd/res/chill/domain/tatallias/LaMauditeTest.java
> Add La Maudite with tests

- src/main/java/ch/heigvd/res/chill/domain/ga3tan/Sapporo.java
- src/test/java/ch/heigvd/res/chill/domain/ga3tan/SapporoTest.java
> Fb add sapporo

- src/main/java/ch/heigvd/res/chill/domain/ga3tan/Grimbergen.java
- src/test/java/ch/heigvd/res/chill/domain/ga3tan/GrimbergenTest.java
> Fb add grimbergen clean

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/GuinnessSmooth.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/GuinnessSmoothTest.java
> Add GuinnessSmooth with tests

- src/main/java/ch/heigvd/res/chill/domain/texx94/Corona.java
- src/test/java/ch/heigvd/res/chill/domain/texx94/CoronaTest.java
> Corona à disposition

- src/main/java/ch/heigvd/res/chill/domain/mtutic/Pan.java
- src/test/java/ch/heigvd/res/chill/domain/mtutic/PanTest.java
> Add Pan with tests

- src/main/java/ch/heigvd/res/chill/domain/GODOmegaPi/Beer1664.java
- src/test/java/ch/heigvd/res/chill/domain/GODOmegaPi/Beer1664Test.java
> Brench 1664 cleaned

- src/main/java/ch/heigvd/res/chill/domain/GODOmegaPi/Beer88.java
- src/test/java/ch/heigvd/res/chill/domain/GODOmegaPi/Beer88Test.java
> Brench 88 cleaned

- src/main/java/ch/heigvd/res/chill/domain/StefanDejanovicHeig/_1664.java
- src/test/java/ch/heigvd/res/chill/domain/StefanDejanovicHeig/_1664Test.java
> Add 1664 beer

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/Mutzig.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/MutzigTest.java
> Add Mutzig with tests

- src/main/java/ch/heigvd/res/chill/domain/joshuaGomesDaCosta/SuperBock.java
- src/test/java/ch/heigvd/res/chill/domain/joshuaGomesDaCosta/SuperBockTest.java
> add superbock

- src/main/java/ch/heigvd/res/chill/domain/joshuaGomesDaCosta/CocaCola.java
- src/test/java/ch/heigvd/res/chill/domain/joshuaGomesDaCosta/CocaColaTest.java
> added cocacola

- src/main/java/ch/heigvd/res/chill/domain/boosterloop/SuzeCoca.java
- src/test/java/ch/heigvd/res/chill/domain/boosterloop/SuzeCocaTest.java
> Added Suze Coca with tests

- src/main/java/ch/heigvd/res/chill/domain/joshuaGomesDaCosta/Cardinal.java
- src/test/java/ch/heigvd/res/chill/domain/joshuaGomesDaCosta/CardinalTest.java
I couldn't split my first PR because the first time I create the 3class in one commit
Close issue #668
> 2try:one feature per commit

- src/main/java/ch/heigvd/res/chill/domain/zereddiamond/FriMousse.java
- src/test/java/ch/heigvd/res/chill/domain/zereddiamond/FriMousseTest.java
I cleaned and add FriMousse. In the future I will pay attention to back in branch master BEFORE create a new branch
> Clean and add FriMousse

- src/main/java/ch/heigvd/res/chill/domain/batach31/LesMurailles.java
- src/test/java/ch/heigvd/res/chill/domain/batach31/LesMuraillesTest.java
> Added cleaned version of les murailles and tests

- src/main/java/ch/heigvd/res/chill/domain/batach31/Karmeliet.java
- src/test/java/ch/heigvd/res/chill/domain/batach31/KarmelietTest.java
> Added Karmeliet feature with tests cleaned version

- src/main/java/ch/heigvd/res/chill/domain/edinem/Leffe.java
- src/test/java/ch/heigvd/res/chill/domain/edinem/LeffeTest.java
Adding leffe beer. Tests ok.
Closes #681
> Adding leffe beer

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/Baileys.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/BaileysTest.java
> Add Baileys with tests

- src/main/java/ch/heigvd/res/chill/domain/mercierjo/Merjo.java
- src/test/java/ch/heigvd/res/chill/domain/mercierjo/MerjoTest.java
> Add Merjo bier with tests

- src/main/java/ch/heigvd/res/chill/domain/tiagoquin/Moretti.java
- src/test/java/ch/heigvd/res/chill/domain/tiagoquin/MorettiTest.java
Voici mes deux fichiers (main et test) pour la bière Moretti
> Ajout de la birra Moretti

- src/main/java/ch/heigvd/res/chill/domain/mtutic/Lasko.java
- src/test/java/ch/heigvd/res/chill/domain/mtutic/LaskoTest.java
> Add Lasko with tests

- src/main/java/ch/heigvd/res/chill/domain/petit1suisse/FalseBeer.java
- src/test/java/ch/heigvd/res/chill/domain/petit1suisse/FalseBeerTest.java
> add FasleBeer

- src/main/java/ch/heigvd/res/chill/domain/VictorTruan/Bintang.java
- src/test/java/ch/heigvd/res/chill/domain/VictorTruan/BintangTest.java
> Ajout de la Bintang

- src/main/java/ch/heigvd/res/chill/domain/kaerdhalis/SangdEncre.java
- src/test/java/ch/heigvd/res/chill/domain/kaerdhalis/SangdEncreTest.java
> add SangdEncre

- src/main/java/ch/heigvd/res/chill/domain/MichaelDaSilva/CurryWurst.java
- src/test/java/ch/heigvd/res/chill/domain/MichaelDaSilva/CurryWurstTest.java
Closes #699 - Adding food in the bar, some CurryWurst
> Add CurryWurst

- src/main/java/ch/heigvd/res/chill/domain/linois/Cuvee.java
- src/test/java/ch/heigvd/res/chill/domain/linois/CuveeTest.java
Closes #548 
I followed the steps of #448 and split the two beers.
> Add Cuvée des Trolls with tests

- src/main/java/ch/heigvd/res/chill/domain/goturak/Carapils.java
- src/test/java/ch/heigvd/res/chill/domain/goturak/CarapilsTest.java
it should (hopefully) be correct now
> added and tested carapils

- src/main/java/ch/heigvd/res/chill/domain/goturak/DeadPonyClub.java
- src/test/java/ch/heigvd/res/chill/domain/goturak/DeadPonyClubTest.java
>  added and tested Dead Pony Club

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/Martini.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/MartiniTest.java
> Add Martini with tests

- src/main/java/ch/heigvd/res/chill/domain/fabano237/Castel.java
- src/test/java/ch/heigvd/res/chill/domain/fabano237/CastelTest.java
> the clean version beer Castel

- src/main/java/ch/heigvd/res/chill/domain/fabano237/Alsace.java
- src/test/java/ch/heigvd/res/chill/domain/fabano237/AlsaceTest.java
I have done my new beer Alsace
> the clean version beer Alsace

- src/main/java/ch/heigvd/res/chill/domain/fabano237/Kronenbourg.java
- src/test/java/ch/heigvd/res/chill/domain/fabano237/KronenbourgTest.java
> the clean version beer Kronenbourg

- src/main/java/ch/heigvd/res/chill/domain/fabano237/Guiness.java
- src/test/java/ch/heigvd/res/chill/domain/fabano237/GuinessTest.java
> the clean version beer Guiness

- src/main/java/ch/heigvd/res/chill/domain/CrescenceK/MalibuAnanas.java
- src/test/java/ch/heigvd/res/chill/domain/CrescenceK/MalibuAnanasTest.java
> Add MalibuAnanas with tests

- src/main/java/ch/heigvd/res/chill/domain/edinem/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/edinem/GuinnessTest.java
Guiness beer added. Tests ok. closes #734
> adding guinness beer

- src/main/java/ch/heigvd/res/chill/domain/Ichimizu/Perlimpimpin.java
- src/test/java/ch/heigvd/res/chill/domain/Ichimizu/PerlimpimpinTest.java
> Adding Perlimpimpin with tests

- src/main/java/ch/heigvd/res/chill/domain/petit1suisse/Wasagidi.java
> correction sur wasagidi

- src/main/java/ch/heigvd/res/chill/domain/CosmicElodie/Celtia.java
- src/test/java/ch/heigvd/res/chill/domain/CosmicElodie/CeltiaTest.java
> Add Celtia with Tests

- src/main/java/ch/heigvd/res/chill/domain/Jael24/Grimbergen.java
- src/test/java/ch/heigvd/res/chill/domain/Jael24/GrimbergenTest.java
> Added Grimbergen

- src/main/java/ch/heigvd/res/chill/domain/Jael24/Brewdog.java
- src/test/java/ch/heigvd/res/chill/domain/Jael24/BrewdogTest.java
> Added Brewdog

- src/main/java/ch/heigvd/res/chill/domain/panticne/Jelen.java
- src/test/java/ch/heigvd/res/chill/domain/panticne/JelenTest.java
> Add Jelen with tests

- src/main/java/ch/heigvd/res/chill/domain/panticne/ImaginaryBeer.java
- src/test/java/ch/heigvd/res/chill/domain/panticne/ImaginaryBeerTest.java
> Add ImaginaryBeer with tests

- src/main/java/ch/heigvd/res/chill/domain/RengokuryuuHonokaCrimsonflame/Udon.java
- src/test/java/ch/heigvd/res/chill/domain/RengokuryuuHonokaCrimsonFlame/UdonTest.java
Hey, I Added udon to the menu. close #756
> I added Udon for tommorow's challenge.

- src/test/java/ch/heigvd/res/chill/domain/RengokuryuuHonokaCrimsonFlame/CrackersTest.java
I forgot to rename the methode in the previous pull request.
> I just changed a method name

- src/main/java/ch/heigvd/res/chill/domain/volkan05/SuperBock.java
- src/test/java/ch/heigvd/res/chill/domain/volkan05/SuperBockTest.java
I added SuperBock. Closes #760
> Adding some delicious SuperBock

- src/main/java/ch/heigvd/res/chill/domain/volkan05/Guinness.java
- src/test/java/ch/heigvd/res/chill/domain/volkan05/GuinnessTest.java
Adding delicious Guinness. Closes #764
> Adding Guinness

- src/main/java/ch/heigvd/res/chill/domain/MaximilianCVogel/VanDeKeizer.java
- src/test/java/ch/heigvd/res/chill/domain/MaximilianCVogel/VanDeKeizerTest.java
> Added Van de Kaizer

- src/main/java/ch/heigvd/res/chill/domain/mercierjo/Kilkenny.java
- src/test/java/ch/heigvd/res/chill/domain/mercierjo/KilkennyTest.java
> Add Kilkenny features with test

- src/main/java/ch/heigvd/res/chill/domain/ercclpn/FallBeer.java
- src/test/java/ch/heigvd/res/chill/domain/ercclpn/FallBeerTest.java
Please have a look at my code. It should close #776 .
> Add Fall Beer and tests

- chill.iml
- src/main/java/ch/heigvd/res/chill/domain/ecarpita93/Peroni.java
- src/test/java/ch/heigvd/res/chill/domain/ecarpita93/PeroniTest.java
removed modified chill.iml from original pr. This should solve issue and closes #201
> Fb add peroni beer

- chill.iml
- src/main/java/ch/heigvd/res/chill/domain/ecarpita93/Peroni.java
- src/test/java/ch/heigvd/res/chill/domain/ecarpita93/PeroniTest.java
I have implemented the Peroni beer to the project. Closes #201
> Peroni Beer implemented with tests

- src/main/java/ch/heigvd/res/chill/domain/sjaubain/Farmer.java
- src/test/java/ch/heigvd/res/chill/domain/sjaubain/FarmerTest.java
> Added Farmer with tests

- src/main/java/ch/heigvd/res/chill/domain/playjul306/PinotNoir.java
- src/test/java/ch/heigvd/res/chill/domain/playjul306/PinotNoirTest.java
I created a Pinot Noir. Closes #802
> Add a Pinot Noir
